# Generated by Django 4.2.4 on 2023-08-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_isbn_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='date_return',
            field=models.DateField(),
        ),
    ]
